### ISSUE TITLE
Add One to One Relationship without Double Fields

### ISSUE THREAD

**Issue by calben** [graphql-compose/graphql-compose#152]
Hullo everyone,

I have a question moreso than an issue, but I didn't see another spot to ask questions so here goes!

I have type `Student` and type `Counselor` with a one to many relationship between the two.
In the Northwind example, I see adding relations is done by adding an ID field and then creating a relation with a findOne for the ID in the appropriate collection.
This is pretty straightforward, but in my own application it had an unexpected side effect where a `Student` would get both a `counselor` and a `counselorID` such that the record in the database looks like this:

```
{
   "_id":"5c004aa3bcb34c08f04cf3d5",
   "name":"bob",
   "email":"bob@bob.com",
   "__v":0,
   "counselor":"5c0040caf8db0401301f85dd",
   "counselorID":"5c0040caf8db0401301f85dd"
}
```

Is this a necessary evil or is there a way to reduce this so that there can be only one field or the other?

My relation looks like this:

```
const Student = mongoose.model('Student', {
    name: String,
    email: String,
    counselorID: { type: Schema.Types.ObjectId, ref: 'Counselor' },
});

const Counselor = mongoose.model('Counselor', {
    name: String,
    email: String,
    studentIDs: [{ type: Schema.Types.ObjectId, ref: 'Student' }]
});

const customizationOptions = {};
const StudentTC = composeWithMongoose(Student, customizationOptions);
const CounselorTC = composeWithMongoose(Counselor, customizationOptions);

StudentTC.addRelation('counselor', {
    resolver: () => CounselorTC.getResolver('findOne'),
    prepareArgs: {
        filter : source => ({ _id: source.counselorID }),
        skip: null,
        sort: null,
    }
})
```

Using this I can correctly make nested requests with `student { counselor { name } }` , but it looks like not quite what I would want.
However, the extra ID field makes me feel I'm doing things wrong.

Thanks for any help or advice!

**Comment by nodkz** [comment]
With `students` try the following code:

```diff
CounselorTC.addRelation('students', {
    resolve: () => StudentTC.getResolver('findMany'),
    prepareArgs: {
        filter: source => ({
            counselorID: source._id
        }),
    },
-    projection: { counselorID: true },
+    projection: { _id: true }, // in projection must be listed a used `source` fields 
})
```
It will be very strange if it will work, cause `_id` populated automatically. I think that problem in data types - in the query used ObjectId, but in db this field stored as a string.

Try to enable mongoose debug and look what queries sended to mongoDB:
```js
import mongoose from 'mongoose';
mongoose.set('debug', true);
```

**Comment by nodkz** [comment]
I think that you may completely remove `counselorID` from db and the code. Keep just one field. 

1) `addRelation` should override default `counselor` field with a complex object.

2) And if you want to get counselor ID without loading a record from db `student { counselor { _id } }` - you may add a new computable field to your type:
```js
StudentTC.addFields({
  counselorId: {
    type: 'MongoId',
    resolve: source => source.counselor,
    projection: { counselor: true },
  },
});
``` 
And you can call such query `student { counselorId }`.

**Comment by calben** [comment]
Hey @nodkz , thanks for the response!!

Looks like if you change the type of counselorID to Schema.Types.ObjectID, the extra field won't be created without needing to use add field.
Unfortunately, adding the projection `_id: true` to the students relation doesn't seem to do the trick.

I'm updating the original post with the code I'm using now that has the counselor nested type working correctly.
The odd thing about the counselor { students } is that the relation isn't even added to the schema, so I can't test it.
An error gets thrown before a call is made to mongo.

```
              "GraphQLError: Cannot query field \"students\" on type \"Counselor\".",
              "    at Object.Field (s:\\Git\\OnTrackServer\\node_modules\\graphql\\validation\\rules\\FieldsOnCorrectType.js:64:31)",
              "    at Object.enter (s:\\Git\\OnTrackServer\\node_modules\\graphql\\language\\visitor.js:333:29)",
              "    at Object.enter (s:\\Git\\OnTrackServer\\node_modules\\graphql\\language\\visitor.js:384:25)",
              "    at visit (s:\\Git\\OnTrackServer\\node_modules\\graphql\\language\\visitor.js:251:26)",
              "    at Object.validate (s:\\Git\\OnTrackServer\\node_modules\\graphql\\validation\\validate.js:63:22)",
              "    at validate (s:\\Git\\OnTrackServer\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:172:32)",
              "    at Object.<anonymous> (s:\\Git\\OnTrackServer\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:113:38)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (s:\\Git\\OnTrackServer\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:4:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by nodkz** [comment]
It's became too difficult to find some trivial error from comments 😅

Can you provide this code via reproducible repo, eg via fork of https://github.com/graphql-compose/graphql-compose-boilerplate
Thanks.

**Comment by calben** [comment]
Oh yeah for sure!  I'll post it shortly! 😄
