### ISSUE TITLE
[Only TypeScript users]: RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by nodkz** [graphql-compose/graphql-compose#191]
If you got `RangeError: Maximum call stack size exceeded` with graphql-compose@7.0.0 under TypeScript when building your app via `tsc`:

```txt
> tsc

/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:72973
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at __generator (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:30:13)
    at getUnmatchedProperties (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37203:20)
    at getUnmatchedProperty (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37237:20)
    at typesDefinitelyUnrelated (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37245:19)
    at inferFromObjectTypes (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37544:22)
```

Congrats! 🎉 You reach some uncovered by TypeScript situation. It very strange behavior and happens very rare.

The issue about this problem already open in typescript repo: https://github.com/Microsoft/TypeScript/issues/31230

## Workaround:

Try to find self-referenced types (User used User) and mark them as `any`:

```diff
User.addResolver({
-  type: User,
+  type: User as any, 
});
```

After that `tsc` should work normally.

**Comment by JadenH** [comment]
I am currently running into this. Does this occur if the type is cloned?
