### ISSUE TITLE
addResolver stopped working for filterArgs

### ISSUE THREAD

**Issue by ziedHamdi** [graphql-compose/graphql-compose#195]
Hi,

I migrated my project dependencies to "graphql-compose-mongoose"  "version": "7.0.1", and my filters stopped working : 

I have a generic method that I use to add filter inputs like 
```
addEntityByLocationSearch('connection')
addEntityByLocationSearch('findMany')
```

this is the corpus of the method
```
const addEntityByLocationSearch = function (resolverName) {
	console.log( "adding entity filter by location for ", resolverName, " in ", EntityTC._gqType )
	const extendedResolver = EntityTC.getResolver(resolverName).addFilterArg({
		name: 'loc',
		type: InputLatLngTC,
		description: 'Search around a given location (lat, lng) in priority',
		query: (query, value, resolveParams) => {
			// FIXME do localized query
			// query.name = new RegExp(value, 'i');
		},
	});
	extendedResolver.name = resolverName;
	EntityTC.addResolver(extendedResolver);
}
```

I get an error in my graphQL saying that cloc does not exist.

When I introspected my shcema in memory I found that the type used is FilterEntityInput, and querying gql about it, I don't find any field named "loc"
```
{
  __type(name: "FilterEntityInput") {
    name
    inputFields {
      name
      type {
        name
        description
      }
    }
  }
}

```

Did the syntax change?

**Comment by nodkz** [comment]
I don't see any problems with your code. For your use case, the syntax stays the same.

You may try to add test case here https://github.com/graphql-compose/graphql-compose/blob/80661343ce019b5c5354ce95238027b340288b8c/src/__tests__/Resolver-test.js#L613-L726

If you find and provide broken case via PR, I'll fix it.

PS. I think that problem somewhere in another part of the code. Maybe `InputLatLngTC` is undefined, or something other. For checking hoisting problem you may try to use closure for type property: `type: () => InputLatLngTC`.

**Comment by ziedHamdi** [comment]
Ok, so there's maybe an error in the sequence of calls, the weired thing is that it was working with 5.x versions, it stopped as soon as I updated my g-c-mongoose dependency.

thanks for the tests link, I'll check what's inside my instance as you did

**Comment by nodkz** [comment]
Yep, really weird. I try to carefully introduce breaking changes. And what you got is abnormal situation.

Did you upgrade both g-c and g-c-mongoose?

**Comment by ziedHamdi** [comment]
Sorry for the delay,

This is what yarn list returns: 
yarn list v1.13.0
├─ graphql-compose-connection@6.0.2
├─ graphql-compose-mongoose@7.0.1
├─ graphql-compose-pagination@6.0.2
└─ graphql-compose@7.0.2

**Comment by ziedHamdi** [comment]
If I remove all dependencies leaving only "graphql-compose-mongoose": "latest", graphql-compose is not installed, does g-c-mogoose ship its own dependency?

D:\Zied\work\weally\server>yarn list --pattern compose
yarn list v1.13.0
├─ graphql-compose-connection@6.0.2
├─ graphql-compose-mongoose@7.0.1
└─ graphql-compose-pagination@6.0.2

**Comment by ziedHamdi** [comment]
By reinstalling dependencies I see there's an issue in g-c:

warning " > graphql-compose-mongoose@7.0.1" has unmet peer dependency "graphql-compose@>=7.0.1".
warning "graphql-compose-mongoose > graphql-compose-pagination@6.0.2" has unmet peer dependency "graphql-compose@>=7.0.0".
warning "graphql-compose-mongoose > graphql-compose-connection@6.0.2" has unmet peer dependency "graphql-compose@>=7.0.0".

how should I solve that?

**Comment by ziedHamdi** [comment]
So bad news,

I isolated the code so that it checks if the field was added just after adding it, and yet it doesn't work

```
import expect from 'expect'
import {
	graphql,
	GraphQLString,
	GraphQLInputObjectType,
	GraphQLInt,
	GraphQLFloat,
	GraphQLNonNull,
	GraphQLObjectType,
	GraphQLEnumType,
	GraphQLList,
} from 'graphql';

function verifyFilterArgs(resolver) {
	const filterCfg = resolver.getArgConfig('filter');
	expect(filterCfg.type).toBeInstanceOf(GraphQLInputObjectType);
	const filterITC = schemaComposer.createInputTC((filterCfg.type));
	const nameRegexpType = filterITC.getFieldType('nameRegexp');
	expect(nameRegexpType.ofType).toBe(GraphQLString);
	console.log( "verification ok" )
}

const addEntityNameRegexpSearch = function (resolverName) {
	const extendedResolver = EntityTC.getResolver(resolverName).addFilterArg({
		name: 'nameRegexp',
		type: 'String',
		description: 'Search by name in regExp',
		query: (query, value, resolveParams) => {
			query.name = new RegExp(value, 'i');
		},
	});
	extendedResolver.name = resolverName;
	EntityTC.addResolver(extendedResolver);

	verifyFilterArgs(extendedResolver)
}

```

**Comment by ziedHamdi** [comment]
Please notice when I compare my code with your tests, I don't have the param: filterTypeNameFallback. Is it a necessaty field? anyway I think that if the operation of addFilterArg doesn't succeed, an exception should be thrown immediately instead of ignoring the params silently

**Comment by ziedHamdi** [comment]
Hi,

I cloned g-c and modified the test you pointed me to as follows _(I had to add filterTypeNameFallback: 'Toto' to get it work)_:

```
  describe('addFilterArg', () => {
    it('should add arg to filter and setup default value', () => {
      const newResolver = resolver.addFilterArg({
        name: 'nameRegexp',
        type: 'String',
        description: 'Search by name in regExp',
        query: (query, value, resolveParams) => {
          query.name = new RegExp(value, 'i');
        },
        filterTypeNameFallback: 'Toto',
      });

      expect(resolver.hasArg('filter')).toBeFalsy();

      const filterCfg = newResolver.getArgConfig('filter');
      expect(filterCfg).toBeTruthy();
      expect(filterCfg.type).toBeInstanceOf(GraphQLInputObjectType);
      // expect(filterCfg.defaultValue).toEqual({ age: 20 });

      const filterITC = schemaComposer.createInputTC((filterCfg.type: any));
      expect((filterITC.getField('nameRegexp'): any).description).toBe('Search by name in regExp');
      const nameType: any = filterITC.getFieldType('nameRegexp');
      expect(nameType).toBeInstanceOf(GraphQLScalarType);
      expect(nameType.ofType).toBe(GraphQLString);
    });
//...
```

Running the test gives me the following error (the line 637 is the last line, expect(nameType.ofType).toBe(GraphQLString) :) 
So the result is different from what I get when I run in my project with the 7.0.3 version. here the field is found but it has no type. I don't know what to do next...

```
Error: expect(received).toBe(expected) // Object.is equality

Expected: "String"
Received: undefined

Difference:

  Comparing two different types of values. Expected object but received undefined.
    at Object.it (D:\Zied\work\graphql-compose\src\__tests__\Resolver-test.js:637:31)
    at Object.asyncJestTest (D:\Zied\work\graphql-compose\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (D:\Zied\work\graphql-compose\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (<anonymous>)
    at mapper (D:\Zied\work\graphql-compose\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (D:\Zied\work\graphql-compose\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
```

**Comment by nodkz** [comment]
Sorry for delay. I had 3 talks and 2 workshops in past week. Tomorrow night I'll go hone. So I try to answer you at the end of week. Too tired and my brain doesn't work.

**Comment by ziedHamdi** [comment]
Ok thanks, too much work for me too, I understand you very well :)

**Comment by ziedHamdi** [comment]
Hi Pavel,

Were you able to take a look at the issue ?

**Comment by nodkz** [comment]
I'm working on this. Right now I resolving the problem with peer dependencies.

Please, try to update all packages g-c.

**Comment by nodkz** [comment]
With test above with error for line 637:

You should remove this line. The scalar type does not have `ofType` property. So you check have no sense.

----

You need to create minimal repro repo with your problem. Cause I don't see any problem, except just fixed peer dependencies with provided information from you.

**Comment by ziedHamdi** [comment]
Ok Pavel,

I'll try to do that tomorrow, again sorry for the delay, I was busy outside the development process

**Comment by ziedHamdi** [comment]
Hi  Pavel @nodkz ,

I finally [reproduced the bug in a project](https://github.com/ziedHamdi/gqlc) i've put on github: 

For a reason I don't understand at all, things work fine with only EntityTC added, but as soon as I add EntityGroupTC, the field is not added to the server anymore, even though, if I check for it immediately after adding it, it is present

I tried to change the name of the field "nameRegexp" thinking there was a name conflict between the two entities, but it didn't help

**Comment by ziedHamdi** [comment]
Ok, found it!!!

It is because I was calling composeWithMongoose(Entity) in the two files : it seams all settings made in Entity are deleted even if I didn't change anything in the schemaComposer, this is a dangerous behavior : schemas are handled globally and reset on each call of composeWithMongoose even if I didn't ask for any change in the schema

My workaround is to reuse the instance created in ./gqlc/entity in entityGroup instead of calling composeWithMongoose when I need to wrap a resolver in another file, but this is a bug in my opinion...

**Comment by ziedHamdi** [comment]
Hi @nodkz, should I close this bug and add the feature as a separate bug?

**Comment by nodkz** [comment]
Thanks for debugging!!! Let continue discussion in this issue.

Yep, the problem in calling `composeWithMongoose` multiple times. In my code I create TC only once and then import in other places its instance.

If you look at this code:
https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/composeWithMongoose.js#L118-L148

... you may see that:
- 127: `convertModelToGraphQL()` inside will reuse existed `ObjectTypeComposer`
- BUT lines 141-143 will recreate resolvers `createResolvers` and remove old ones with your logic 

So we need to make a decision:
1) Throw Error if somebody calls `composeWithMongoose` with the same model in the second and further times. (This decision may have break somebody code on startup phase and can be easily fixed)
2) Return existed ObjectTypeComposer without errors without recreating resolvers. (This decision may break somebody code, in a case when used different options for `composeWithMongoose` method. And debug this situation will be quite difficult.)
3) Leave current code as-is. Maybe add some console.warn() message.

What do you think?

**Comment by ziedHamdi** [comment]
Hi Pavel,

Sorry, I just saw your answer since I went back to my issue to see how I solved a similar problem :)

I would definitely opt for the number 2 solution since I may need to resolve my model differently in different situations. If I want to reuse the same logic I will have the choice to find the instance I built in a different place.

Anyway, I think every object oriented developer will expect to have a distinct instance for each call to `composeWithMongoose` and not having things overlapping in the background. That's why I expressed the problem as dangerous (since repeating the exact same code could lead to different results depending on code that was run somewhere else)

For the backward compatibility issue with older versions, I think it is sufficient to change the major version number and to put that change as a warning in the change log

Thanks for asking me my opinion as a user, and thanks for the work you've done, it is a rocket starter to use graphql-compose-mongoose especially if I use apollo from the client side, changes to the db are directly impacted on the front end and client cache without effort
