### ISSUE TITLE
SchemaComposer.set() accept only TypeComposers. You provide with key "PaginationInfo" the following wrong value ObjectTypeComposer

### ISSUE THREAD

**Issue by corydeppen** [graphql-compose/graphql-compose#198]
I'm running into the following error when trying to run the app after a production build using webpack (via [Backpack](https://github.com/jaredpalmer/backpack)). For some reason I don't see this when running a development build, though.

```
GRAPHQL-COMPOSE DEPRECATION: SchemaComposer.set() accept only TypeComposers. You provide with key "PaginationInfo" the following wrong value ObjectTypeComposer({ schemaComposer: SchemaComposer, _gqType: PaginationInfo, _gqcFields: Object({ currentPage: Object({ type: NonNullComposer({ ofType: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }) }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "currentPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NonNullType", type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), perPage: Object({ type: NonNullComposer({ ofType: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }) }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "perPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NonNullType", type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), pageCount: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "pageCount", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), itemCount: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "itemCount", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), hasNextPage: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Boolean, _gqcSerialize: [function serializeBoolean], _gqcParseValue: [function coerceBoolean], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "hasNextPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Boolean", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), hasPreviousPage: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Boolean, _gqcSerialize: [function serializeBoolean], _gqcParseValue: [function coerceBoolean], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "hasPreviousPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Boolean", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }) }), _gqcInterfaces: [], _gqcExtensions: Object({ directives: [] }) }). 
    SchemaComposer.set (/Users/username/path/to/project/build/main.js:40590:30)
--> preparePaginationInfoTC (/Users/username/path/to/project/build/main.js:271940:6)
    preparePaginationTC (/Users/username/path/to/project/build/main.js:271965:15)
    preparePaginationResolver (/Users/username/path/to/project/build/main.js:141449:58)
    pagination (/Users/username/path/to/project/build/main.js:5762:20)


/Users/username/path/to/project/build/main.js:40973
      throw e;
      ^

Error: TypeError[.pageInfo]: Cannot convert to InputType the following value: Object({ type: NonNullComposer({ ofType: ObjectTypeComposer({ schemaComposer: SchemaComposer, _gqType: PaginationInfo, _gqcFields: Object({ currentPage: Object({ type: NonNullComposer({ ofType: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }) }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "currentPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NonNullType", type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), perPage: Object({ type: NonNullComposer({ ofType: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }) }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "perPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NonNullType", type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), pageCount: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "pageCount", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), itemCount: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "itemCount", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Int", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), hasNextPage: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Boolean, _gqcSerialize: [function serializeBoolean], _gqcParseValue: [function coerceBoolean], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "hasNextPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Boolean", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }), hasPreviousPage: Object({ type: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Boolean, _gqcSerialize: [function serializeBoolean], _gqcParseValue: [function coerceBoolean], _gqcParseLiteral: [function parseLiteral] }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: "Name", value: "hasPreviousPage", loc: [object Object] }), arguments: [], type: Object({ kind: "NamedType", name: Object({ kind: "Name", value: "Boolean", loc: [object Object] }), loc: [object Object] }), directives: [], loc: [object Object] }), extensions: Object({ directives: [] }) }) }), _gqcInterfaces: [], _gqcExtensions: Object({ directives: [] }) }) }), description: "Information to aid in pagination." })
    at TypeMapper.convertOutputFieldConfig (/Users/username/path/to/project/build/main.js:40970:13)
    at Object.keys.forEach.name (/Users/username/path/to/project/build/main.js:40980:27)
    at Array.forEach (<anonymous>)
    at TypeMapper.convertOutputFieldConfigMap (/Users/username/path/to/project/build/main.js:40979:32)
    at ObjectTypeComposer.addFields (/Users/username/path/to/project/build/main.js:36794:93)
    at Function.createTemp (/Users/username/path/to/project/build/main.js:36709:12)
    at Function.create (/Users/username/path/to/project/build/main.js:36664:21)
    at SchemaComposer.createObjectTC (/Users/username/path/to/project/build/main.js:40304:51)
    at preparePaginationTC (/Users/username/path/to/project/build/main.js:271952:39)
    at preparePaginationResolver (/Users/username/path/to/project/build/main.js:141449:58)
    at pagination (/Users/username/path/to/project/build/main.js:5762:20)
    at names.forEach.resolverName (/Users/username/path/to/project/build/main.js:6371:26)
    at Array.forEach (<anonymous>)
    at createResolvers (/Users/username/path/to/project/build/main.js:6366:9)
    at composeWithMongoose (/Users/username/path/to/project/build/main.js:6317:5)
    at Module.<anonymous> (/Users/username/path/to/project/build/main.js:2170:56)
```

graphql-compose: 7.3.0
graphql-compose-mongoose: 7.1.2
graphql-compose-pagination: 6.0.3

**Comment by rockus123** [comment]
I get this exact same error with composeWithMongoose(myModel) with latest graphql-compose 7.3.0, grapqh-compose-mongoose 7.1.3, graphql-compose-connection: 6.0.3and graphql-compose-pagination 6.0.3.   

2019-08-22 08:36:42.316 [error] uncaughtException: TypeError[.pageInfo]: Cannot convert to InputType the following value: Object({ type: NonNullComposer({ ofType: ObjectTypeComposer({ schemaComposer: SchemaComposer, _gqType: PaginationInfo, _gqcFields: Object({ currentPage: Object({ type: NonNullComposer({ ofType: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseV...
   at TypeMapper.convertOutputFieldConfig 
    at Array.forEach (<anonymous>)
    at TypeMapper.convertOutputFieldConfigMap 
    at ObjectTypeComposer.addFields
    at Function.createTemp
    at Function.create
    at SchemaComposer.createObjectTC (
    at preparePaginationTC
    at preparePaginationResolver
    at pagination
    at Array.forEach (<anonymous>)
    at createResolvers
    at composeWithMongoose\bundle.js:88532:5)
    at Module../src/server/model/MyModel.js 

 But revert back to my previous versions before updating to the latest graphql-compose latest, everything works with no error.  

      "graphql-compose": "^5.12.0",
      "graphql-compose-connection": "^4.0.0",
      "graphql-compose-leveler": "^0.2.0",
      "graphql-compose-mongoose": "^5.2.1",
      "graphql-compose-pagination": "^4.0.0"

**Comment by nodkz** [comment]
It may be an error with a package manager. Try to remove your `node_modules` folder and install all packages from scratch.

I have different projects which normally work with v7 and v6.

### For graphql-compose: 7.3.0
graphql-compose-mongoose 7.1.3
graphql-compose-connection 6.0.3
graphql-compose-pagination 6.0.3

### For graphql-compose: 6.3.5
graphql-compose-mongoose 6.2.0
graphql-compose-connection 5.0.0
graphql-compose-pagination 5.1.0

**Comment by rockus123** [comment]
I deleted the node_modules and npm install.  But same error.  I tried 3 times.  Next try would be to start a new project and trace from there.

**Comment by rockus123** [comment]
Hi Nodkz,

I reduced my server.js to just this and still get the error below.  Something has changed between graphql-compose-mongoose version 5 and the latest version.  All I do is just do composeWithMongoose(User).  This is as barebone as I can reduce the basic code to.  Please help.  Thanks. 

```
import mongoose from 'mongoose'

import { composeWithMongoose } from 'graphql-compose-mongoose/node8'

const UserSchema = new mongoose.Schema({
   userName: {
      type: String
   }
})

const User = mongoose.model('User', UserSchema)
const UserTC = composeWithMongoose(User)
console.log("hello")
```


The error is: 

`GRAPHQL-COMPOSE DEPRECATION: SchemaComposer.set() accept only TypeComposers. You provide with key "PaginationInfo" the following wrong value ObjectTypeComposer({ schemaComposer: SchemaComposer, _gqType: PaginationInfo,`

**Comment by rockus123** [comment]
My package.json is also contains almost nothing, barebone:

```
{
   "name": "testcompose",
   "version": "1.0.0",
   "description": "",
   "main": "index.js",
   "scripts": {
      "dev:server": "npm-run-all -s build:dev:server dev:watch:start:server",
      "dev:watch:start:server": "npm-run-all -p watch:dev:server start:dev:server",
      "build:dev:server": "rimraf build/server && webpack --mode development --config webpack.dev.server.js",
      "watch:dev:server": "webpack --mode development --config webpack.dev.server.js --watch",
      "start:dev:server": "nodemon --inspect --harmony --watch build/server build/server/bundle.js",
      "test": "echo \"Error: no test specified\" && exit 1"
   },
   "author": "",
   "license": "ISC",
   "dependencies": {
      "bufferutil": "^4.0.1",
      "graphql": "^14.5.4",
      "graphql-compose": "^7.3.0",
      "graphql-compose-connection": "^6.0.3",
      "graphql-compose-mongoose": "^7.1.3",
      "graphql-compose-pagination": "^6.0.3",
      "graphql-tools": "^4.0.5",
      "mongoose": "^5.6.13",
      "utf-8-validate": "^5.0.2"
   },
   "devDependencies": {
      "@babel/cli": "^7.6.0",
      "@babel/core": "^7.6.0",
      "@babel/node": "^7.6.1",
      "@babel/runtime": "^7.6.0",
      "babel-loader": "^8.0.6",
      "cross-env": "^5.2.1",
      "nodemon": "^1.19.2",
      "npm-run-all": "^4.1.5",
      "webpack": "^4.39.3",
      "webpack-cli": "^3.3.8"
   }
}
```

**Comment by rockus123** [comment]
ok, I create a small graphql server with graph-compose-mongoose without webpack, then it works.  But once I use webpack to build and run this small server, it failed with the same error:
```

GRAPHQL-COMPOSE DEPRECATION: SchemaComposer.set() accept only TypeComposers. You provide with key "PaginationInfo" the following wrong value ObjectTypeComposer({ schemaComposer: SchemaComposer, _gqType: PaginationInfo,...

Error: TypeError[.pageInfo]: Cannot convert to InputType the following value: Object({ type: NonNullComposer({ ofType: ObjectTypeComposer({ schemaComposer: SchemaComposer, _gqType: PaginationInfo, _gqcFields: Object({ currentPage: Object({ type: NonNullComposer({ ofType: ScalarTypeComposer({ schemaComposer: SchemaComposer, _gqType: Int, _gqcSerialize: [function serializeInt], _gqcParseValue: [function coerceInt], _gqcParseLiteral: [function parseLiteral] }) }), args: Object({  }), description: undefined, deprecationReason: undefined, astNode: Object({ kind: "FieldDefinition", description: undefined, name: Object({ kind: ...
```

So is it webpack or graphql-compose-mongoose latest version.  With graphl-compose-mongoose version 5, everything is fine with the same latest webpack version.  So I believe the latest version of graphql-compose-mongoose is broken with the latest webpack.  

Nodk, Please help.  Thanks.

**Comment by nodkz** [comment]
Please provide a public repro repo. I try to figure out wha causet the problem.

**Comment by rockus123** [comment]
I send you the rar file TestComposeApolloWebpack.rar to your email.  The instructions are in readme.md.  Thanks for your help.

**Comment by rockus123** [comment]
After 10 days including heavy debugging, I found the issue to be in webpack.  It seems that webpack handles mjs files incorrectly.  So to fix the above issue, you have to:

npm install -D webpack-modules

and then, in your webpack config.

const WebpackModules = require('webpack-modules');
 
module.exports = {
  // ...
  plugins: [
    new WebpackModules()
  ]


Nodkz, thanks for your willingness to help and the great library.

**Comment by YoonChangKook** [comment]
@rockus123 
SOOOOOOOOOOOO THANK YOU FOR YOUR DDDDDDDDDDDDEBUGGG!!!!!!!!!
<img width="147" alt="스크린샷 2020-02-21 오후 2 38 25" src="https://user-images.githubusercontent.com/16934567/75007267-e7078700-54b7-11ea-95fe-894420848410.png">

**Comment by jade-feret** [comment]
@rockus123 
solution did not work for me. 
I am trying to deploy to AWS lambda using serverless and I am using webpack-serverless to transform to commonjs2.

What worked: downgrading to webpack 4 and changing adding this rule to my webpack config:
```

{
                test: /\.m?js$/,
                use: [
                    {
                        loader: "babel-loader",
                    },
                ],
                type: "javascript/auto",
            },
```
Hope it helps someone!
