### ISSUE TITLE
resolver.addFilterArg not working without clear reason why

### ISSUE THREAD

**Issue by ziedHamdi** [graphql-compose/graphql-compose#222]
Hi Pavel,

I'm going mad since I don't get why the code inside my addFilterArg is not working. here's my code

`function addQueryFields(resolverName) {
	const queryResolver = ComplaintActionTC.getResolver(resolverName);
	queryResolver.addFilterArg({
		name: 'complaintId',
		type: 'String',
		description: 'complaintId',
		query: (query, complaintId, resolveParams) => { // eslint-disable-line
			console.log( "################## will query with complaintId ", complaintId )
			if (complaintId != null) {
				query['entity.complaintId'] = complaintId
			}
		},
	})
	queryResolver.addFilterArg({
		name: 'value',
		type: 'String',
		description: 'value',
		query: (query, value, resolveParams) => { // eslint-disable-line
			if (value != null) query['state.value'] = value
		},
	})
	queryResolver.name = resolverName;
	ComplaintActionTC.addResolver(queryResolver);
}

addQueryFields("connection")

schemaComposer.Query.addFields({
	complaintActionConnection: ComplaintActionTC.getResolver('connection').wrapResolve(next => async rp => {
		const {user} = rp.context
		const filter = rp.args.filter
		console.log("###################### rp.args.filter ", filter)
		return await next(rp)
	})
});
`

I have the line in the logs that shows the argument is present

> ###################### rp.args.filter  { complaintId: '5dc4914d60c2db15b441e08c' }

But the line `console.log( "################## will query with complaintId ", complaintId )` never executes.

My issue is more about "how to debug why the resolver doesn't pass in" than how to solve this issue, since I can do a manual mongoose query and solve the problem, but I'd like to use the library, and maybe I don't know how to debug what's happening inside of it.

I know for sure that the filter argument complaintId is present in the resolver since the query is accepted, but how to know why the query method is not executed, or how to know what query is executed? I need some best practices in this case please

Best regards,
Zied

**Comment by ziedHamdi** [comment]
![image](https://user-images.githubusercontent.com/7271508/68466969-adb35000-0215-11ea-84ec-2f3c229ee1a7.png)

As you can see from the image, I don't know what you pass me in the `next` variable, and I can't know which code will execute. Stepping into it with the debugger doesn't work. I know the code is somewhere in the connection package, but it's tedious work

How can I activate logs on the connection package for example to understand why the query method is skipped?...

**Comment by ziedHamdi** [comment]
I added the following code to addQueryFields defined above:

```
	const oldResolve = queryResolver.resolve
	queryResolver.resolve = async (resolveParams) => {
		console.log( "############ resolve params :", resolveParams )
		console.log( "############ resolver:", oldResolve)
		oldResolve(resolveParams)
	}

```

having this final version of the method
```
function addQueryFields(resolverName) {
	const queryResolver = ComplaintActionTC.getResolver(resolverName);
	queryResolver.addFilterArg({
		name: 'complaintId',
		type: 'String',
		description: 'complaintId',
		query: (query, complaintId, resolveParams) => { // eslint-disable-line
			if (complaintId != null) {
				query['entity.complaintId'] = complaintId
			}
			console.log( "################## will query with complaintId ", query )
		},
	})
	queryResolver.addFilterArg({
		name: 'value',
		type: 'String',
		description: 'value',
		query: (query, value, resolveParams) => { // eslint-disable-line
			if (value != null) query['state.value'] = value
			console.log( "################## will query with value ", query )
		},
	})

	const oldResolve = queryResolver.resolve
	queryResolver.resolve = async (resolveParams) => {
		console.log( "############ resolve params :", resolveParams )
		console.log( "############ resolver:", oldResolve)
		oldResolve(resolveParams)
	}
	queryResolver.name = resolverName;
	ComplaintActionTC.addResolver(queryResolver);
}

```

The output is the following:
```###################### rp.args.filter  { complaintId: '5dc4925b0e258d22b46e3255' }
############ resolve params : { source: undefined,
  args:
   { first: 5,
     filter: { complaintId: '5dc4925b0e258d22b46e3255' },
     sort: { _id: -1 } },
  context:
   { user:
      { id: '5dc42880f3c674109439f4ac',
        name: 'Emna Riahi',
        roles: [],
        picture: '/api/profile_pic/5dc42881bfbaa18f3687f927',
        picId: '5dc42881bfbaa18f3687f927',
        facebook: [Object],
        iat: 1573136513 },
     sessionID: undefined },
  info:
   { fieldName: 'complaintActionConnection',
     fieldNodes: [ [Object] ],
     returnType: ComplaintActionConnection,
     parentType: Query,
     path: { prev: undefined, key: 'complaintActionConnection' },
     schema:
      GraphQLSchema {
        __validationErrors: [],
        __allowedLegacyNames: [],
        _queryType: Query,
        _mutationType: Mutation,
        _subscriptionType: undefined,
        _directives: [Array],
        astNode: undefined,
        extensionASTNodes: undefined,
        _typeMap: [Object],
        _possibleTypeMap: {},
        _implementations: {} },
     fragments: {},
     rootValue: undefined,
     operation:
      { kind: 'OperationDefinition',
        operation: 'query',
        name: [Object],
        variableDefinitions: [Array],
        directives: [],
        selectionSet: [Object],
        loc: [Object] },
     variableValues: { issueId: '5dc4925b0e258d22b46e3255' } },
  projection:
   { count: {},
     pageInfo:
      { startCursor: {},
        endCursor: {},
        hasNextPage: {},
        hasPreviousPage: {},
        __typename: {} },
     edges: { cursor: {}, node: [Object], __typename: {} },
     __typename: {},
     first:
      { type: [ScalarTypeComposer],
        description:
         'Forward pagination argument for returning at most first edges' },
     after:
      { type: [ScalarTypeComposer],
        description:
         'Forward pagination argument for returning at most first edges' },
     last:
      { type: [ScalarTypeComposer],
        description:
         'Backward pagination argument for returning at most last edges' },
     before:
      { type: [ScalarTypeComposer],
        description:
         'Backward pagination argument for returning at most last edges' },
     filter:
      { type: [InputTypeComposer], description: 'Filter by fields' },
     sort:
      { type: [EnumTypeComposer],
        defaultValue: [Object],
        description: 'Sort argument for data ordering' } } }
############ resolver: async resolveParams => {
        const value = _objectPath.default.get(resolveParams, ['args', 'filter', name]);

        if (value !== null && value !== undefined) {
          if (!resolveParams.rawQuery) {
            resolveParams.rawQuery = {}; // eslint-disable-line
          }

          await query(resolveParams.rawQuery, value, resolveParams);
        }

        return resolveNext(resolveParams);
      }```

But I cannot test the code in my method since I don't have access to `_objectPath`

(I tried to replace it by oldResolve._objectPath, but for some reason, it is not recognized). Anyway, it seams that value is null or undefined

I also tried to call query manually skipping the not null check and passing 'test' as a value:

```
		if (!resolveParams.rawQuery) {
			resolveParams.rawQuery = {}; // eslint-disable-line
		}

		await oldResolve.query(resolveParams.rawQuery, 'test', resolveParams);

```
but the resolver does not have a query method at all!!!
```
graphQl error stack:  TypeError: oldResolve.query is not a function
    at query (D:\Zied\work\weally\server\src\graphql/complaintAction.js:107:20)
    at next (D:\Zied\work\weally\server\src\graphql/complaintAction.js:61:16)
```

**Comment by ziedHamdi** [comment]
Ok I found it!!!

The resolver is not modified, but a new one is created at the call of `addFilterArg`
changing the code 

```
	const queryResolver = ComplaintActionTC.getResolver(resolverName);
	queryResolver.addFilterArg({
```
to the following

	`const queryResolver = ComplaintActionTC.getResolver(resolverName).addFilterArg({`

makes everything work fine.

I think this is an issue, since the call to the  `addFilterArg` method changes partially the resolver, adding it an input without adding the logic behind it.

There's also a naming error, since the method  `addFilterArg` is understood as adding a filter arg, if it doesn't add it, it should be named  `createResolverWithFilterArg` or similarily, but definitely not 'add'

This bug took me 4 hours to fix, and I think that if I didn't have a working example elsewhere, it would have taken me a lot more. I was supposing the field was added since the query was accepted, the easiest way to fix it I think would be to make the method either

- add both the param and the query method

- add none of them, and it would be better to rename it in this case

Best regards,
Zied
