### ISSUE TITLE
[Bug] Cannot read property 'getTypeName' of undefined

### ISSUE THREAD

**Issue by blueandhack** [graphql-compose/graphql-compose#232]
When upgrade graphql-compose to 7.10.0, meet with the error.

```
/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:263
        value: atc.getTypeName()
                   ^

TypeError: Cannot read property 'getTypeName' of undefined
    at getTypeNode (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:263:20)
    at /Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:299:13
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:291:21)
    at getObjectTypeDefinitionNode (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:38:13)
    at ObjectTypeComposer.getType (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ObjectTypeComposer.js:672:76)
    at ListComposer.getType (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ListComposer.js:22:49)
    at Resolver.getType (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/Resolver.js:90:22)
    at Resolver.getFieldConfig (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/Resolver.js:622:18)
    at ObjectTypeComposer._relationWithResolverToFC (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1320:34)
    at /Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1257:105
    at getFC (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/createThunkedObjectProxy.js:17:48)
    at Object.get (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/createThunkedObjectProxy.js:28:14)
    at /Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:299:28
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:291:21)
    at getObjectTypeDefinitionNode (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/utils/definitionNode.js:38:13)
    at ObjectTypeComposer.getType (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ObjectTypeComposer.js:672:76)
    at Resolver.getType (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/Resolver.js:90:22)
    at Resolver.getFieldConfig (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/Resolver.js:622:18)
    at ObjectTypeComposer._relationWithResolverToFC (/Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1320:34)
    at /Users/XXXUSER/Projects/XXXProject/XXXXXXProject/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1257:105
```

My develop environment
```
yarn versions v1.22.0
{
  yarn: '1.22.0',
  node: '13.7.0',
  v8: '7.9.317.25-node.28',
  uv: '1.34.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '79',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.1',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```
✨  Done in 0.02s.

**Comment by nodkz** [comment]
Thanks for reporting!

Please check a new version. 
If you meet with other errors please let me know.
