### ISSUE TITLE
v8 breaks `GraphQLJSON` usage in `createObjectTC`

### ISSUE THREAD

**Issue by rijkvanzanten** [graphql-compose/graphql-compose#334]
In v7.x, the following used to work:

```ts
import { GraphQLJSON, SchemaComposer } from 'graphql-compose';

const sc = new SchemaComposer();

sc.createObjectTC({
	name: 'example',
	fields: {
		exampleField: {
			type: GraphQLJSON,
		},
	},
});
```

However, in v8.0.1, this is throwing

```
Error: TypeError[example.exampleField]: Cannot convert to OutputType the following value: Object({ type: JSON })
    at TypeMapper.convertOutputFieldConfig (/path/to/node_modules/graphql-compose/src/TypeMapper.ts:399:13)
    at ObjectTypeComposer.setField (/path/to/node_modules/graphql-compose/src/ObjectTypeComposer.ts:436:40)
    at /path/to/node_modules/graphql-compose/src/ObjectTypeComposer.ts:449:12
    at Array.forEach (<anonymous>)
    at ObjectTypeComposer.addFields (/path/to/node_modules/graphql-compose/src/ObjectTypeComposer.ts:448:28)
    at Function.createTemp (/path/to/node_modules/graphql-compose/src/ObjectTypeComposer.ts:312:12)
    at Function.create (/path/to/node_modules/graphql-compose/src/ObjectTypeComposer.ts:257:21)
    at SchemaComposer.createObjectTC (/path/to/node_modules/graphql-compose/src/SchemaComposer.ts:529:31)
    at Object.<anonymous> (/path/to/graphql-debug.ts:5:4)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

I can confirm this is just the `GraphQLJSON` type. Replacing that with a regular GraphQL generic scalar like `GraphQLString` works just fine.

**Comment by rijkvanzanten** [comment]
It does seem to function properly when using an inline arrow function for `type`:

```
...
		exampleField: {
			type: () => GraphQLJSON,
		},
...
```

**Comment by rijkvanzanten** [comment]
FWIW it doesn't matter whether or not this type is imported from `graphql-compose` or directly from `graphql-type-json`

**Comment by rijkvanzanten** [comment]
This is a bit of a guess, but might be worth a look. It could be that this check:

https://github.com/graphql-compose/graphql-compose/blob/58a5d46b2fb29cd16fd668b6f5e0ee806fb56154/src/TypeMapper.ts#L339

fails, as `GraphQLScalarType` is imported from a local `./graphql` path, which re-exports from `graphql`. If `graphql-type-json` extends the `GraphQLScalarType` from a different instance of `graphql`, it'll fail the instanceof check, as they won't share the same underlying `GraphQLScalarType` 🤔

**Comment by rijkvanzanten** [comment]
My hunch was right, but the cause different.. For whatever reason, `npm` started resolving to a different versioned copy of `graphql` under my monorepo after upgrading `graphql-compose` 🤔 As with many unexplainable issues in JS nowadays, a full re-install of all `node_modules` did the trick. 

Thanks for reading along, and to future readers: When in doubt, try reinstalling node_modules.
